# Generated by Django 6.0.6 on 2026-09-09 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='page',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
