# Generated by Django 6.0.6 on 2026-09-08 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srm', '0003_purchaseorder_payment_terms_supplierpayment'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders_tenant', to='tenants.company'),
        ),
    ]
