# Generated by Django 6.0.6 on 2026-09-09 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_client_tenant_alter_lead_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='design_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='lead',
            name='design_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
