# Generated by Django 6.0.6 on 2026-09-17 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0006_lead_design_snapshot_lead_design_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="share_token",
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
