# Generated by Django 6.0.6 on 2026-09-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onboarding_progress',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
