# Generated by Django 6.0.6 on 2026-09-08 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_employee_tenant'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='tenant',
            field=models.ForeignKey(default='e6e5a7be-40c9-4b20-a789-99c39111b303', on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='tenants.company'),
            preserve_default=False,
        ),
    ]
