# Generated by Django 6.0.6 on 2026-06-30 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='is_back_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workorder',
            name='room_id_ref',
            field=models.PositiveIntegerField(blank=True, help_text='CRM Room ID this work order was generated from', null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='sent_cabinet_ids',
            field=models.JSONField(blank=True, default=list, help_text='List of cabinet ids from the room already included in this or prior work orders'),
        ),
    ]
