# Generated by Django 6.0.6 on 2026-07-24 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_supplier_default_payment_terms'),
        ('manufacturing', '0002_workorder_is_back_order_workorder_room_id_ref_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuttingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thickness', models.DecimalField(decimal_places=2, max_digits=6)),
                ('kerf', models.DecimalField(decimal_places=2, default=4.0, help_text='blade width mm', max_digits=4)),
                ('trim_top', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('trim_left', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('OPTIMIZED', 'Optimized'), ('EXPORTED', 'Exported')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cutting_jobs', to='inventory.material')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutting_jobs', to='manufacturing.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='CuttingLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_index', models.PositiveIntegerField()),
                ('waste_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layouts', to='manufacturing.cuttingjob')),
            ],
        ),
        migrations.CreateModel(
            name='CuttingPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=200)),
                ('width', models.DecimalField(decimal_places=2, max_digits=8)),
                ('height', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('grain_locked', models.BooleanField(default=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='manufacturing.cuttingjob')),
            ],
        ),
        migrations.CreateModel(
            name='PartPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.DecimalField(decimal_places=2, max_digits=8)),
                ('y', models.DecimalField(decimal_places=2, max_digits=8)),
                ('width', models.DecimalField(decimal_places=2, max_digits=8)),
                ('height', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rotated', models.BooleanField(default=False)),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='manufacturing.cuttinglayout')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='manufacturing.cuttingpart')),
            ],
        ),
        migrations.CreateModel(
            name='StockSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thickness', models.DecimalField(decimal_places=2, max_digits=6)),
                ('width', models.DecimalField(decimal_places=2, help_text='mm', max_digits=8)),
                ('height', models.DecimalField(decimal_places=2, help_text='mm', max_digits=8)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grain_direction', models.CharField(choices=[('length', 'Length'), ('width', 'Width'), ('none', 'None')], default='length', max_length=10)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_sheets', to='inventory.material')),
            ],
        ),
        migrations.AddField(
            model_name='cuttinglayout',
            name='sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='layouts', to='manufacturing.stocksheet'),
        ),
    ]
