# Generated by Django 6.0.6 on 2026-09-08 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0003_cuttingjob_cuttinglayout_cuttingpart_partplacement_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionstation',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_stations', to='tenants.company'),
        ),
        migrations.AddField(
            model_name='stocksheet',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_sheets_tenant', to='tenants.company'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='tenants.company'),
        ),
    ]
