# Generated by Django 6.0.6 on 2026-09-08 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0004_productionstation_tenant_stocksheet_tenant_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionstation',
            name='tenant',
            field=models.ForeignKey(default='e6e5a7be-40c9-4b20-a789-99c39111b303', on_delete=django.db.models.deletion.CASCADE, related_name='production_stations', to='tenants.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stocksheet',
            name='tenant',
            field=models.ForeignKey(default='e6e5a7be-40c9-4b20-a789-99c39111b303', on_delete=django.db.models.deletion.CASCADE, related_name='stock_sheets_tenant', to='tenants.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workorder',
            name='tenant',
            field=models.ForeignKey(default='e6e5a7be-40c9-4b20-a789-99c39111b303', on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='tenants.company'),
            preserve_default=False,
        ),
    ]
