# Generated by Django 6.0.6 on 2026-09-09 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='company',
            name='stripe_subscription_id',
        ),
    ]
