# Generated by Django 6.0.6 on 2026-09-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_companysettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymembership',
            name='permissions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
