# Generated by Django 6.0.6 on 2026-09-13 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0021_alter_drawersystem_name_and_more'),
        ('tenants', '0004_companymembership_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadCamImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('bsolid', 'bSolid'), ('cabinetvision', 'Cabinet Vision'), ('alphacam', 'Alphacam'), ('microvellum', 'Microvellum'), ('woodwop', 'WoodWOP')], max_length=20)),
                ('method', models.CharField(choices=[('api', 'API'), ('csv', 'CSV')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('source_file', models.FileField(blank=True, null=True, upload_to='cadcam_imports/')),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cadcam_import_jobs', to='tenants.company')),
            ],
        ),
        migrations.CreateModel(
            name='ImportedPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_code', models.CharField(blank=True, max_length=100)),
                ('sheet_ref', models.CharField(blank=True, max_length=100)),
                ('width_mm', models.DecimalField(decimal_places=2, max_digits=8)),
                ('height_mm', models.DecimalField(decimal_places=2, max_digits=8)),
                ('grain', models.CharField(blank=True, choices=[('H', 'Horizontal'), ('V', 'Vertical')], max_length=1)),
                ('edgeband_top', models.BooleanField(default=False)),
                ('edgeband_bottom', models.BooleanField(default=False)),
                ('edgeband_left', models.BooleanField(default=False)),
                ('edgeband_right', models.BooleanField(default=False)),
                ('edgeband_tape', models.CharField(blank=True, max_length=100)),
                ('machining_ops', models.JSONField(blank=True, default=list)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='cadcam.cadcamimportjob')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cadcam_parts', to='inventory.material')),
            ],
        ),
        migrations.CreateModel(
            name='RemnantOffcut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_ref', models.CharField(blank=True, max_length=100)),
                ('width_mm', models.DecimalField(decimal_places=2, max_digits=8)),
                ('height_mm', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_usable', models.BooleanField(default=False)),
                ('added_to_stock', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offcuts', to='cadcam.cadcamimportjob')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cadcam_offcuts', to='inventory.material')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cadcam_offcuts', to='tenants.company')),
            ],
        ),
    ]
