# Generated by Django 6.0.6 on 2026-06-30 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialTexture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('material_type', models.CharField(choices=[('front', 'Front/Door'), ('worktop', 'Worktop/Countertop')], max_length=10)),
                ('texture_image', models.ImageField(upload_to='material_textures/')),
                ('fallback_hex', models.CharField(default='#FFFFFF', help_text='Used if texture fails to load', max_length=7)),
                ('roughness', models.FloatField(default=0.4)),
                ('metalness', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='textures', to='inventory.supplier')),
            ],
        ),
    ]
