# Generated by Django 6.0.6 on 2026-06-30 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_materialtexture'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialtexture',
            name='board_height',
            field=models.PositiveIntegerField(default=1220, help_text='Board height in mm'),
        ),
        migrations.AddField(
            model_name='materialtexture',
            name='board_width',
            field=models.PositiveIntegerField(default=2440, help_text='Board width in mm'),
        ),
        migrations.AddField(
            model_name='materialtexture',
            name='finish',
            field=models.CharField(choices=[('matt', 'Matt'), ('gloss', 'Gloss'), ('wood', 'Wood'), ('metal', 'Metal'), ('other', 'Other')], default='matt', max_length=10),
        ),
        migrations.AddField(
            model_name='materialtexture',
            name='price_per_board',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='materialtexture',
            name='thickness',
            field=models.PositiveIntegerField(default=18, help_text='Board thickness in mm'),
        ),
    ]
