# Generated by Django 6.0.6 on 2026-07-01 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_materialtexture_add_carcass_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialtexture',
            name='texture_physical_height_mm',
            field=models.PositiveIntegerField(default=600, help_text='Real-world height this texture image represents (mm). E.g. 600 for a 600 mm tile sample, 1220 for a full-board photo.'),
        ),
        migrations.AlterField(
            model_name='materialtexture',
            name='texture_physical_width_mm',
            field=models.PositiveIntegerField(default=600, help_text='Real-world width this texture image represents (mm). Used to scale grain correctly in 3D view. E.g. 600 for a 600 mm tile sample, 2440 for a full-board photo.'),
        ),
    ]
