# Generated by Django 6.0.6 on 2026-07-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_materialtexture_texture_physical_height_mm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialtexture',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
