# Generated by Django 6.0.6 on 2026-07-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_materialtexture_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialtexture',
            name='core_material',
            field=models.CharField(choices=[('particleboard', 'Particleboard / Melamine'), ('mdf', 'MDF'), ('hdf', 'HDF'), ('plywood', 'Plywood'), ('solid_wood', 'Solid Wood'), ('compact', 'Compact Laminate')], default='particleboard', help_text='Board substrate/core', max_length=20),
        ),
    ]
