# Generated by Django 6.0.6 on 2026-07-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_materialtexture_core_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrawerSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('brand', models.CharField(blank=True, default='', max_length=100)),
                ('box_construction', models.CharField(choices=[('metal_sided', 'Metal-sided (system provides box)'), ('wood_box', 'Wood box + runners')], default='wood_box', max_length=15)),
                ('price_per_set', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
