# Generated by Django 6.0.6 on 2026-07-09 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_drawersystem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, default='', max_length=100)),
                ('model_name', models.CharField(max_length=150)),
                ('material', models.CharField(choices=[('stainless_steel', 'Stainless Steel'), ('granite_composite', 'Granite Composite (Silgranit)'), ('ceramic', 'Ceramic/Fireclay'), ('other', 'Other')], default='stainless_steel', max_length=20)),
                ('color', models.CharField(blank=True, default='', help_text='e.g. Anthracite, White, Steel Grey', max_length=50)),
                ('color_hex', models.CharField(default='#4a4a4a', help_text='Approximate render color', max_length=7)),
                ('cavity_count', models.PositiveSmallIntegerField(choices=[(1, 'Single Bowl'), (2, 'Double Bowl')], default=1)),
                ('mount_type', models.CharField(choices=[('undermount', 'Undermount'), ('topmount', 'Top-mount / Drop-in'), ('flushmount', 'Flush-mount')], default='undermount', max_length=15)),
                ('shape', models.CharField(choices=[('rectangular', 'Rectangular'), ('rounded', 'Rounded Corners'), ('d_shape', 'D-Bowl')], default='rectangular', max_length=20)),
                ('width_mm', models.PositiveIntegerField(help_text='Overall sink width (mm)')),
                ('depth_mm', models.PositiveIntegerField(help_text='Overall sink depth, front-to-back (mm)')),
                ('bowl_depth_mm', models.PositiveIntegerField(default=180, help_text='Bowl depth from rim down (mm)')),
                ('cutout_width_mm', models.PositiveIntegerField(blank=True, help_text='Required countertop cutout width (mm) for fabrication, if different from overall width', null=True)),
                ('cutout_depth_mm', models.PositiveIntegerField(blank=True, help_text='Required countertop cutout depth (mm) for fabrication, if different from overall depth', null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='sinks/')),
                ('roughness', models.FloatField(default=0.35)),
                ('metalness', models.FloatField(default=0.85)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'brand', 'model_name'],
            },
        ),
    ]
