# Generated by Django 6.0.6 on 2026-07-15 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_sink'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='category',
            field=models.CharField(blank=True, choices=[('raw_material', 'Raw Material'), ('hardware', 'Hardware'), ('glass', 'Glass'), ('countertop', 'Countertop/Stone'), ('appliance', 'Appliance'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='lead_time_days',
            field=models.PositiveIntegerField(blank=True, help_text='Typical lead time in days', null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='payment_terms',
            field=models.CharField(blank=True, help_text='e.g. Net 30, 50% deposit / 50% on delivery', max_length=100),
        ),
    ]
