# Generated by Django 6.0.6 on 2026-07-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_supplier_category_supplier_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='default_payment_terms',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('net7', 'Net 7 days'), ('net30', 'Net 30 days'), ('net60', 'Net 60 days')], default='cod', max_length=10),
        ),
    ]
