# Generated by Django 6.0.6 on 2026-07-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_supplier_default_payment_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='has_grain',
            field=models.BooleanField(default=False, help_text='Whether this material has visible directional grain (e.g. wood-look laminate)'),
        ),
    ]
