# Generated by Django 6.0.6 on 2026-07-25 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_material_has_grain'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialtexture',
            name='stock_material',
            field=models.ForeignKey(blank=True, help_text='Which inventory Material/StockSheet this design finish maps to for cutting purposes', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_textures', to='inventory.material'),
        ),
    ]
