# Generated by Django 6.0.6 on 2026-07-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_materialtexture_stock_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='board_height',
            field=models.PositiveIntegerField(blank=True, default=1220, help_text='Board height in mm', null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='board_thickness',
            field=models.PositiveIntegerField(blank=True, default=18, help_text='Board thickness in mm', null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='board_width',
            field=models.PositiveIntegerField(blank=True, default=2440, help_text='Board width in mm', null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='fallback_hex',
            field=models.CharField(blank=True, default='#FFFFFF', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='finish',
            field=models.CharField(blank=True, choices=[('matt', 'Matt'), ('gloss', 'Gloss'), ('wood', 'Wood'), ('metal', 'Metal'), ('other', 'Other')], default='matt', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='material_type',
            field=models.CharField(blank=True, choices=[('front', 'Front/Door'), ('worktop', 'Worktop/Countertop'), ('carcass', 'Carcass/Interior')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='metalness',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='roughness',
            field=models.FloatField(blank=True, default=0.4, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='texture_image',
            field=models.ImageField(blank=True, null=True, upload_to='material_textures/'),
        ),
    ]
