# Generated by Django 6.0.6 on 2026-07-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_material_board_height_material_board_thickness_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='core_material',
            field=models.CharField(blank=True, choices=[('particleboard', 'Particleboard / Melamine'), ('mdf', 'MDF'), ('hdf', 'HDF'), ('plywood', 'Plywood'), ('solid_wood', 'Solid Wood'), ('compact', 'Compact Laminate')], default='particleboard', help_text='Board substrate/core', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='price_per_board',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='texture_physical_height_mm',
            field=models.PositiveIntegerField(blank=True, default=600, help_text='Real-world height this texture image represents (mm)', null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='texture_physical_width_mm',
            field=models.PositiveIntegerField(blank=True, default=600, help_text='Real-world width this texture image represents (mm), for scaling grain in 3D view', null=True),
        ),
    ]
