# Generated by Django 6.0.6 on 2026-07-25 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_material_core_material_material_price_per_board_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MaterialTexture',
        ),
    ]
