# Generated by Django 6.0.6 on 2026-09-08 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_delete_materialtexture'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawersystem',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drawer_systems', to='tenants.company'),
        ),
        migrations.AddField(
            model_name='material',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials_tenant', to='tenants.company'),
        ),
        migrations.AddField(
            model_name='sink',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sinks', to='tenants.company'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='tenants.company'),
        ),
    ]
