# Generated by Django 6.0.6 on 2026-09-08 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_drawersystem_tenant_material_tenant_sink_tenant_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawersystem',
            name='tenant',
            field=models.ForeignKey(default='e6e5a7be-40c9-4b20-a789-99c39111b303', on_delete=django.db.models.deletion.CASCADE, related_name='drawer_systems', to='tenants.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='material',
            name='tenant',
            field=models.ForeignKey(default='e6e5a7be-40c9-4b20-a789-99c39111b303', on_delete=django.db.models.deletion.CASCADE, related_name='materials_tenant', to='tenants.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sink',
            name='tenant',
            field=models.ForeignKey(default='e6e5a7be-40c9-4b20-a789-99c39111b303', on_delete=django.db.models.deletion.CASCADE, related_name='sinks', to='tenants.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplier',
            name='tenant',
            field=models.ForeignKey(default='e6e5a7be-40c9-4b20-a789-99c39111b303', on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='tenants.company'),
            preserve_default=False,
        ),
    ]
