# Generated by Django 6.0.6 on 2026-09-09 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_alter_material_sku_alter_material_unique_together'),
        ('tenants', '0002_remove_company_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawersystem',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='drawersystem',
            unique_together={('tenant', 'name')},
        ),
    ]
