# Generated by Django 6.0.6 on 2026-09-16 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_alter_drawersystem_name_and_more'),
        ('tenants', '0004_companymembership_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CabinetTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=20)),
                ('subtype', models.CharField(default='Custom', max_length=100)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('depth', models.PositiveIntegerField()),
                ('wall_height', models.PositiveIntegerField(blank=True, null=True)),
                ('elevation', models.PositiveIntegerField(blank=True, null=True)),
                ('door_count', models.PositiveIntegerField(blank=True, null=True)),
                ('shelves', models.PositiveIntegerField(blank=True, null=True)),
                ('drawer_system', models.CharField(blank=True, default='', max_length=100)),
                ('icon', models.CharField(default='specialty_custom', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('source_conversation', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cabinet_templates', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_cabinet_templates', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_templates', to='tenants.company')),
            ],
        ),
    ]
