# Generated by Django 6.0.6 on 2026-10-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_drawersystem_price_per_set_c_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='price_unit',
            field=models.CharField(choices=[('board', 'Per Board'), ('lm', 'Per Linear Meter'), ('m2', 'Per m²')], default='board', help_text='What price_per_board is quoted per -- countertop suppliers often quote per running meter', max_length=10),
        ),
    ]
